// THIS FILE IS AUTO-GENERATED - DO NOT EDIT MANUALLY
// It is generated by serialArduinoErrorConfig.go

// device.ledpanel.arduino.error.hpp
#ifndef DEVICE_LEDPANEL_ARDUINO_ERROR_HPP
#define DEVICE_LEDPANEL_ARDUINO_ERROR_HPP

#include "Arduino.h"

const String ErrorLatchTimeout = "Elati"; // param: min latch wait time ms
const String ErrorNoCommand = "Encmd"; // character: command
const String ErrorNotDefinedCommand = "Endcm"; // character: command
const String ErrorNotEnoughBytesColorParam = "Enebs"; // character: current char, param: current number of bytes
const String ErrorNotHexColorParameter = "Enhxc"; // character: current char
const String ErrorNotHexNumberParameter = "Enhxn"; // character: current char
const String ErrorNotInitialized = "Enini"; // character: current char
const String ErrorNumberParameterOverflowEqualsNumLeds = "Enpeq"; // character: current char, param: number paramerter
const String ErrorNumberParameterOverflow = "Enpov"; // character: current char, param: number paramerter
const String ErrorNoReturn = "Enret"; // character: current char
const String ErrorUnknownCommand = "Eucmd"; // character: current char, param: command
const String ErrorNoInitialisationPossible = "Euini";
const String ErrorUnknownLetter = "Eulet"; // character: letter, param: charType (D=undefined, C=command, H=hexnumber, R=return)
const String ErrorUnknownReturn = "Euret"; // character: current char
const String ErrorWrongParity = "Ewpar"; // character: last char

#endif // device.ledpanel.arduino.error.hpp
